// (payload) route group layout — CSS imports only.
// The actual Payload admin shell (RootLayout with html/body) is in:
//   app/(payload)/admin/layout.tsx  ← auto-generated by Payload CLI
// This file must NOT re-wrap with RootLayout to avoid double html/body nesting.
import '@payloadcms/next/css'
import './custom.scss'
import React from 'react'

export default function PayloadGroupLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}

