export const runtime = 'edge'
import { getPayload } from 'payload'
import config from '../../../../payload.config'
import { NextResponse } from 'next/server'
import type { CollectionSlug } from 'payload'

export const GET = async () => {
  // Security: Only allow seeding in development or with proper secret
  if (process.env.NODE_ENV === 'production' && process.env.ALLOW_SEED !== 'true') {
    return NextResponse.json(
      { error: 'Seed endpoints are disabled in production' },
      { status: 403 }
    )
  }

  const payload = await getPayload({ config })

  // Type assertion for collections that might not be in generated types yet
  const collections = {
    members: 'members' as CollectionSlug,
    'board-members': 'board-members' as CollectionSlug,
    supervisors: 'supervisors' as CollectionSlug,
    employees: 'employees' as CollectionSlug,
    'guest-book': 'guest-book' as CollectionSlug,
    suggestions: 'suggestions' as CollectionSlug,
    meetings: 'meetings' as CollectionSlug,
    logs: 'logs' as CollectionSlug,
    'mail-log': 'mail-log' as CollectionSlug,
  }

  try {
    // 1. Buku Induk Anggota (Members)
    // Note: memberId will be auto-generated by beforeChange hook
    const m1 = await payload.create({
      collection: collections.members,
      draft: false,
      data: {
        memberId: '', // Will be auto-generated by hook
        fullName: 'H. Sudirman',
        nik: '3201012345678901',
        membershipStatus: 'active',
        joinDate: '2025-01-01T00:00:00.000Z',
      } as any,
    })
    const m2 = await payload.create({
      collection: collections.members,
      draft: false,
      data: {
        memberId: '', // Will be auto-generated by hook
        fullName: 'Dr. Wahyudi',
        nik: '3201019876543210',
        membershipStatus: 'active',
        joinDate: '2025-01-01T00:00:00.000Z',
      } as any,
    })
    const m3 = await payload.create({
      collection: collections.members,
      draft: false,
      data: {
        memberId: '', // Will be auto-generated by hook
        fullName: 'Rina Kartika',
        nik: '3201015678901234',
        membershipStatus: 'active',
        joinDate: '2025-06-01T00:00:00.000Z',
      } as any,
    })

    // 2. Daftar Pengurus (BoardMembers)
    await payload.create({
      collection: collections['board-members'],
      draft: false,
      data: {
        member: m1.id,
        position: 'chairman',
        periodStart: '2025-01-01T00:00:00.000Z',
        periodEnd: '2030-01-01T00:00:00.000Z',
        status: 'active',
      } as any,
    })

    // 3. Daftar Pengawas (Supervisors)
    await payload.create({
      collection: collections.supervisors,
      draft: false,
      data: {
        member: m2.id,
        position: 'member',
        periodStart: '2025-01-01T00:00:00.000Z',
        periodEnd: '2030-01-01T00:00:00.000Z',
        status: 'active',
      } as any,
    })

    // 4. Daftar Karyawan (Employees)
    await payload.create({
      collection: collections.employees,
      draft: false,
      data: {
        member: m3.id,
        position: 'teller',
        department: 'Simpan Pinjam',
        joinDate: '2025-06-01T00:00:00.000Z',
        employmentStatus: 'contract',
        status: 'active',
      } as any,
    })

    // 5. Daftar Buku Tamu (GuestBook)
    await payload.create({
      collection: collections['guest-book'],
      draft: false,
      data: {
        date: new Date().toISOString(),
        guestName: 'Drs. Supriadi',
        title: 'Kepala Dinas Kopearasi',
        organization: 'Dinas Kopearasi Kab. Bandung',
        purpose: 'visit',
        followUpActions: 'Belum ada',
      } as any,
    })

    // 6. Saran & Anjuran (Suggestions)
    await payload.create({
      collection: collections.suggestions,
      draft: false,
      data: {
        date: new Date().toISOString(),
        subject: 'Penambahan Limit Pinjaman Khusus Usaha',
        submittedBy: 'Ahmad Faisal (Anggota)',
        content: 'Mohon dipertimbangkan untuk anggota yang memiliki UMKM bisa dinaikkan limitnya agar lebih membantu modal.',
        status: 'in_review',
      } as any,
    })

    // 7. Ekspedisi Surat (MailLog)
    await payload.create({
      collection: collections['mail-log'],
      draft: false,
      data: {
        date: new Date().toISOString(),
        mailType: 'incoming',
        mailNumber: '001/DKOP/IV/2026',
        senderOrRecipient: 'Dinas Kopearasi',
        subject: 'Undangan Rapat Koordinasi Tahunan',
        notes: 'Disposisi ke Ketua Umum',
      } as any,
    })

    // 8. Buku Kejadian Penting (Logs)
    await payload.create({
      collection: collections.logs,
      draft: false,
      data: {
        date: new Date().toISOString(),
        title: 'Peresmian Aplikasi SIKDMP',
        eventType: 'milestone',
        description: 'Aplikasi SIKDMP sukses diluncurkan hari ini dengan akses untuk admin dan seluruh anggota secara langsung.',
        reportedBy: 'Super Admin',
      } as any,
    })

    // 9. Buku Notulen Rapat (Meetings)
    await payload.create({
      collection: collections.meetings,
      draft: false,
      data: {
        title: 'Rapat Persiapan RAT 2026',
        meetingType: 'pengurus',
        status: 'conducted',
        date: new Date().toISOString(),
        location: 'Kantor Cabang KDMP',
        chairperson: 'H. Sudirman',
        secretary: 'Rina Kartika',
      } as any,
    })

    return new NextResponse(
      '<div style="font-family: sans-serif; padding: 40px; text-align: center;"><h1>✅ 9 Buku Kopearasi Berhasil Diisi!</h1><p>Data dummy untuk seluruh administrasi buku kopearasi (Induk, Pengurus, Surat, Rapat, dsb) telah ditambahkan.</p><p><a href="/admin" style="display:inline-block; margin-top:20px; padding: 10px 20px; background: #DC2626; color: white; text-decoration: none; border-radius: 8px;">Kembali ke Admin Panel</a></p></div>',
      { headers: { 'Content-Type': 'text/html' } }
    )
  } catch (error: unknown) {
    console.error('Seeding 9 Buku Error:', error)
    const errorMessage = error instanceof Error ? error.message : 'Unknown error'
    return NextResponse.json({ error: errorMessage }, { status: 500 })
  }
}
